// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/proto/nlp.proto

package nlp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Doc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Doc) Reset() {
	*x = Doc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_nlp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nlp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_api_proto_nlp_proto_rawDescGZIP(), []int{0}
}

func (x *Doc) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DocToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  uint32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop   uint32 `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Pos    string `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Id     string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	HeadId string `protobuf:"bytes,6,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	Rel    string `protobuf:"bytes,7,opt,name=rel,proto3" json:"rel,omitempty"`
	Lemma  string `protobuf:"bytes,8,opt,name=lemma,proto3" json:"lemma,omitempty"`
}

func (x *DocToken) Reset() {
	*x = DocToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_nlp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocToken) ProtoMessage() {}

func (x *DocToken) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nlp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocToken.ProtoReflect.Descriptor instead.
func (*DocToken) Descriptor() ([]byte, []int) {
	return file_api_proto_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *DocToken) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *DocToken) GetStop() uint32 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *DocToken) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocToken) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *DocToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocToken) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *DocToken) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *DocToken) GetLemma() string {
	if x != nil {
		return x.Lemma
	}
	return ""
}

type DocSpan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  uint32      `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop   uint32      `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Type   string      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Text   string      `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Normal string      `protobuf:"bytes,5,opt,name=normal,proto3" json:"normal,omitempty"`
	Tokens []*DocToken `protobuf:"bytes,6,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *DocSpan) Reset() {
	*x = DocSpan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_nlp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSpan) ProtoMessage() {}

func (x *DocSpan) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nlp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSpan.ProtoReflect.Descriptor instead.
func (*DocSpan) Descriptor() ([]byte, []int) {
	return file_api_proto_nlp_proto_rawDescGZIP(), []int{2}
}

func (x *DocSpan) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *DocSpan) GetStop() uint32 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *DocSpan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DocSpan) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocSpan) GetNormal() string {
	if x != nil {
		return x.Normal
	}
	return ""
}

func (x *DocSpan) GetTokens() []*DocToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type DocSent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  uint32      `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop   uint32      `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Text   string      `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Spans  []*DocSpan  `protobuf:"bytes,4,rep,name=spans,proto3" json:"spans,omitempty"`
	Tokens []*DocToken `protobuf:"bytes,5,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *DocSent) Reset() {
	*x = DocSent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_nlp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSent) ProtoMessage() {}

func (x *DocSent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nlp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSent.ProtoReflect.Descriptor instead.
func (*DocSent) Descriptor() ([]byte, []int) {
	return file_api_proto_nlp_proto_rawDescGZIP(), []int{3}
}

func (x *DocSent) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *DocSent) GetStop() uint32 {
	if x != nil {
		return x.Stop
	}
	return 0
}

func (x *DocSent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocSent) GetSpans() []*DocSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *DocSent) GetTokens() []*DocToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*DocToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Sents  []*DocSent  `protobuf:"bytes,2,rep,name=sents,proto3" json:"sents,omitempty"`
	Spans  []*DocSpan  `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_nlp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nlp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_proto_nlp_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetTokens() []*DocToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *Result) GetSents() []*DocSent {
	if x != nil {
		return x.Sents
	}
	return nil
}

func (x *Result) GetSpans() []*DocSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_api_proto_nlp_proto protoreflect.FileDescriptor

var file_api_proto_nlp_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6c, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0xab, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x6d, 0x6d,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x6d, 0x6d, 0x61, 0x22, 0x96,
	0x01, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x53, 0x70, 0x61, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x6f, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x53,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x44, 0x6f, 0x63, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x05, 0x73, 0x70, 0x61, 0x6e,
	0x73, 0x12, 0x21, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x44, 0x6f, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x73, 0x22, 0x6b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21,
	0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x44, 0x6f, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x44, 0x6f, 0x63, 0x53, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x73, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x44, 0x6f, 0x63, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x05, 0x73, 0x70, 0x61, 0x6e,
	0x73, 0x32, 0x1d, 0x0a, 0x03, 0x4e, 0x4c, 0x50, 0x12, 0x16, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x12, 0x04, 0x2e, 0x44, 0x6f, 0x63, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x6e, 0x6c, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_nlp_proto_rawDescOnce sync.Once
	file_api_proto_nlp_proto_rawDescData = file_api_proto_nlp_proto_rawDesc
)

func file_api_proto_nlp_proto_rawDescGZIP() []byte {
	file_api_proto_nlp_proto_rawDescOnce.Do(func() {
		file_api_proto_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_nlp_proto_rawDescData)
	})
	return file_api_proto_nlp_proto_rawDescData
}

var file_api_proto_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_nlp_proto_goTypes = []interface{}{
	(*Doc)(nil),      // 0: Doc
	(*DocToken)(nil), // 1: DocToken
	(*DocSpan)(nil),  // 2: DocSpan
	(*DocSent)(nil),  // 3: DocSent
	(*Result)(nil),   // 4: Result
}
var file_api_proto_nlp_proto_depIdxs = []int32{
	1, // 0: DocSpan.tokens:type_name -> DocToken
	2, // 1: DocSent.spans:type_name -> DocSpan
	1, // 2: DocSent.tokens:type_name -> DocToken
	1, // 3: Result.tokens:type_name -> DocToken
	3, // 4: Result.sents:type_name -> DocSent
	2, // 5: Result.spans:type_name -> DocSpan
	0, // 6: NLP.Parse:input_type -> Doc
	4, // 7: NLP.Parse:output_type -> Result
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_nlp_proto_init() }
func file_api_proto_nlp_proto_init() {
	if File_api_proto_nlp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_nlp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_nlp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_nlp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocSpan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_nlp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocSent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_nlp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_nlp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nlp_proto_goTypes,
		DependencyIndexes: file_api_proto_nlp_proto_depIdxs,
		MessageInfos:      file_api_proto_nlp_proto_msgTypes,
	}.Build()
	File_api_proto_nlp_proto = out.File
	file_api_proto_nlp_proto_rawDesc = nil
	file_api_proto_nlp_proto_goTypes = nil
	file_api_proto_nlp_proto_depIdxs = nil
}
