// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IndexObject struct {
	ID             string   `json:"id"`
	Type           string   `json:"type"`
	Score          float64  `json:"score"`
	Service        string   `json:"service"`
	IsActive       bool     `json:"isActive"`
	URL            *string  `json:"url,omitempty"`
	Slug           *string  `json:"slug,omitempty"`
	Name           *string  `json:"name,omitempty"`
	Title          *string  `json:"title,omitempty"`
	Picture        *string  `json:"picture,omitempty"`
	Provider       *string  `json:"provider,omitempty"`
	Genres         []string `json:"genres,omitempty"`
	Persons        []string `json:"persons,omitempty"`
	Countries      []string `json:"countries,omitempty"`
	Description    *string  `json:"description,omitempty"`
	Year           *string  `json:"year,omitempty"`
	YearEnd        *string  `json:"yearEnd,omitempty"`
	YearStart      *string  `json:"yearStart,omitempty"`
	AgeRestriction *string  `json:"ageRestriction,omitempty"`
}

type SearchEntity struct {
	End         int     `json:"end"`
	Start       int     `json:"start"`
	Type        string  `json:"type"`
	Value       string  `json:"value"`
	NormalValue *string `json:"normalValue,omitempty"`
}

type SearchIntent struct {
	Name       string  `json:"name"`
	Confidence float64 `json:"confidence"`
}

type SearchResponse struct {
	Documents []*IndexObject          `json:"documents,omitempty"`
	Metadata  *SearchResponseMetadata `json:"metadata"`
}

type SearchResponseMetadata struct {
	Entities []*SearchEntity `json:"entities,omitempty"`
	Intent   *SearchIntent   `json:"intent,omitempty"`
	Query    string          `json:"query"`
}

type SearchWhereInput struct {
	Service *string `json:"service,omitempty"`
	Active  *bool   `json:"active,omitempty"`
}
